# Generated by Django 5.1.6 on 2025-02-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaChef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
